name: ci

on:
  push:
    branches:
      - 'master'

# env:
#   CUR_DATE: $(date +'%Y-%m-%d')
# #   CUR_DATE: "123"
#   CUR_COMMITID: "123"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: set NOW
        run: |
            echo "::set-env name=NOW::$(date +'%Y%m%d')"
      - name: set COMMITID
        run: |
            echo "::set-env name=COMMITID::$(GITHUB_SHA)"
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: hhczy1003/test:ci_${{ env.NOW }}_${{ env.COMMITID }}
          file: docker/Dockerfile
